/*
Catherine Nguyen
CSC 174
Ying Jin
11/15/2020
UPDATED: 11/16/2020 */

/*DROP TRIGGERS */
DROP TRIGGER IF EXISTS Inc_enrollment_number;
DROP TRIGGER IF EXISTS Del_enrollment_number;

/* DROP PROCEDURES */
DROP PROCEDURE IF EXISTS Get_TA;
DROP PROCEDURE IF EXISTS GetStudentCourse;

/* DROP FUNCTION*/
DROP FUNCTION IF EXISTS Course_Instructor;

/* DROP VIEWS */
DROP VIEW IF EXISTS TraditionalCourseView; 
DROP VIEW IF EXISTS OnlineCourseView;
DROP VIEW IF EXISTS TAView;
DROP VIEW IF EXISTS Student_Grade_A;
DROP VIEW IF EXISTS TA_Course;

/* DROP TABLES */
DROP TABLE IF EXISTS TraditionalCourse;
DROP TABLE IF EXISTS Classroom;
DROP TABLE IF EXISTS OnlineCourse;
DROP TABLE IF EXISTS Enrolled;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS TA;
DROP TABLE IF EXISTS Instructor;
DROP TABLE IF EXISTS Student;